collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8566057
  brandStrength: 0.5257788
  lightness: 0.7792696
  brandColors:
    - '#E6E4D7'
    - '#1F1F1D'
    - '#C2B7A4'
    - '#94958D'
    - '#75756B'
  rhythmicContrast: 1
typography_spectrum: 0.4785177
layout_spectrum: 0.4516649
name: Allegro-Bikes
